apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: ${api_advertise_addresses}
etcd:
  endpoints:
  ${etcd_endpoints}
networking:
  podSubnet: "${pod_subnet}" # --pod-network-cidr
  serviceSubnet: "${service_subnet}" # --service-cidr
apiServerCertSANs:
  ${cert_sans}
